package com.example.anno_compiler;

/**
 * Created by zhaochaoyue on 2020/06/09.
 */

public class Consts {
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "Initer";
    public static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler";
    public static final String ANNOTATION_NAME = "com.example.anno.FragDest";
    public static final String KEY_MODULE_NAME = "MYROUTER_MODULE_NAME";
    public static final String TEMPLATE_NAME = "com.zcy.initer.api.IComponentInit";
    public static final String CLASS_INTERFACE_NAME = "com.zcy.initer.api.IClassInit";
    public static final String GENERATE_CLASS_NAME = "_InitImpl";
    public static final String CONTEXT_NAME = "android.content.Context";
    public static final String PACKAGE_OF_GENERATE_FILE = "com.zcy.initer.auto"; //generator class package name
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY INITER.";

    public static final String PROVIDER_ANNOTATION_NAME = "com.hzq.initer.annotation.Provider";
    public static final String PROVIDER_CLASS = "com.zcy.initer.api.IProvider";
    public static final String GENERATE_PROVIDER_CLASS_NAME = "_ProviderImpl";
    public static final String PROVIDER_TEMPLATE_NAME = "com.hzq.initer.api.ProviderMapCreator";
}
